# Generated by Django 2.2.11 on 2020-07-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(max_length=100, verbose_name='Data')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('valor', models.FloatField(max_length=100, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
    ]
