# Generated by Django 2.2.11 on 2020-07-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoboy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregamodel',
            name='data',
            field=models.CharField(max_length=100, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='entregamodel',
            name='valor',
            field=models.CharField(max_length=100, verbose_name='Valor'),
        ),
    ]
