# Generated by Django 2.2.11 on 2020-07-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoboy', '0002_auto_20200709_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregamodel',
            name='pendente',
            field=models.BooleanField(default=True, verbose_name='Pendente'),
        ),
    ]
